[package]
name = "fry-chess"
version = "0.1.0"
authors = ["erol", "stian"]
edition = "2018"

[dependencies]
san-rs = "0"
fen-rs = { path = "../libfen-rs" }
clap = { version = "2.33", default-features = false, features = [ "color" ] }
